<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        // activo=true: Latinoamérica + España + USA por defecto
        $activosPorDefecto = [
            'GT','MX','US','HN','SV','NI','CR','PA','BZ',
            'CO','VE','PE','EC','BO','PY','UY','AR','CL','BR',
            'CU','DO','PR','ES',
        ];

        $paises = [
            ['code' => 'AF', 'name' => 'Afganistán',                    'dial' => '+93',   'orden' => 1],
            ['code' => 'AL', 'name' => 'Albania',                       'dial' => '+355',  'orden' => 2],
            ['code' => 'DE', 'name' => 'Alemania',                      'dial' => '+49',   'orden' => 3],
            ['code' => 'AD', 'name' => 'Andorra',                       'dial' => '+376',  'orden' => 4],
            ['code' => 'AO', 'name' => 'Angola',                        'dial' => '+244',  'orden' => 5],
            ['code' => 'AG', 'name' => 'Antigua y Barbuda',             'dial' => '+1268', 'orden' => 6],
            ['code' => 'SA', 'name' => 'Arabia Saudita',                'dial' => '+966',  'orden' => 7],
            ['code' => 'DZ', 'name' => 'Argelia',                       'dial' => '+213',  'orden' => 8],
            ['code' => 'AR', 'name' => 'Argentina',                     'dial' => '+54',   'orden' => 9],
            ['code' => 'AM', 'name' => 'Armenia',                       'dial' => '+374',  'orden' => 10],
            ['code' => 'AU', 'name' => 'Australia',                     'dial' => '+61',   'orden' => 11],
            ['code' => 'AT', 'name' => 'Austria',                       'dial' => '+43',   'orden' => 12],
            ['code' => 'AZ', 'name' => 'Azerbaiyán',                    'dial' => '+994',  'orden' => 13],
            ['code' => 'BS', 'name' => 'Bahamas',                       'dial' => '+1242', 'orden' => 14],
            ['code' => 'BD', 'name' => 'Bangladés',                     'dial' => '+880',  'orden' => 15],
            ['code' => 'BB', 'name' => 'Barbados',                      'dial' => '+1246', 'orden' => 16],
            ['code' => 'BH', 'name' => 'Baréin',                        'dial' => '+973',  'orden' => 17],
            ['code' => 'BE', 'name' => 'Bélgica',                       'dial' => '+32',   'orden' => 18],
            ['code' => 'BZ', 'name' => 'Belice',                        'dial' => '+501',  'orden' => 19],
            ['code' => 'BJ', 'name' => 'Benín',                         'dial' => '+229',  'orden' => 20],
            ['code' => 'BY', 'name' => 'Bielorrusia',                   'dial' => '+375',  'orden' => 21],
            ['code' => 'BO', 'name' => 'Bolivia',                       'dial' => '+591',  'orden' => 22],
            ['code' => 'BA', 'name' => 'Bosnia y Herzegovina',          'dial' => '+387',  'orden' => 23],
            ['code' => 'BW', 'name' => 'Botsuana',                      'dial' => '+267',  'orden' => 24],
            ['code' => 'BR', 'name' => 'Brasil',                        'dial' => '+55',   'orden' => 25],
            ['code' => 'BN', 'name' => 'Brunéi',                        'dial' => '+673',  'orden' => 26],
            ['code' => 'BG', 'name' => 'Bulgaria',                      'dial' => '+359',  'orden' => 27],
            ['code' => 'BF', 'name' => 'Burkina Faso',                  'dial' => '+226',  'orden' => 28],
            ['code' => 'BI', 'name' => 'Burundi',                       'dial' => '+257',  'orden' => 29],
            ['code' => 'BT', 'name' => 'Bután',                         'dial' => '+975',  'orden' => 30],
            ['code' => 'CV', 'name' => 'Cabo Verde',                    'dial' => '+238',  'orden' => 31],
            ['code' => 'KH', 'name' => 'Camboya',                       'dial' => '+855',  'orden' => 32],
            ['code' => 'CM', 'name' => 'Camerún',                       'dial' => '+237',  'orden' => 33],
            ['code' => 'CA', 'name' => 'Canadá',                        'dial' => '+1',    'orden' => 34],
            ['code' => 'QA', 'name' => 'Catar',                         'dial' => '+974',  'orden' => 35],
            ['code' => 'TD', 'name' => 'Chad',                          'dial' => '+235',  'orden' => 36],
            ['code' => 'CL', 'name' => 'Chile',                         'dial' => '+56',   'orden' => 37],
            ['code' => 'CN', 'name' => 'China',                         'dial' => '+86',   'orden' => 38],
            ['code' => 'CY', 'name' => 'Chipre',                        'dial' => '+357',  'orden' => 39],
            ['code' => 'VA', 'name' => 'Ciudad del Vaticano',           'dial' => '+379',  'orden' => 40],
            ['code' => 'CO', 'name' => 'Colombia',                      'dial' => '+57',   'orden' => 41],
            ['code' => 'KM', 'name' => 'Comoras',                       'dial' => '+269',  'orden' => 42],
            ['code' => 'CG', 'name' => 'Congo',                         'dial' => '+242',  'orden' => 43],
            ['code' => 'CD', 'name' => 'Congo (Rep. Dem.)',              'dial' => '+243',  'orden' => 44],
            ['code' => 'KP', 'name' => 'Corea del Norte',               'dial' => '+850',  'orden' => 45],
            ['code' => 'KR', 'name' => 'Corea del Sur',                 'dial' => '+82',   'orden' => 46],
            ['code' => 'CI', 'name' => 'Costa de Marfil',               'dial' => '+225',  'orden' => 47],
            ['code' => 'CR', 'name' => 'Costa Rica',                    'dial' => '+506',  'orden' => 48],
            ['code' => 'HR', 'name' => 'Croacia',                       'dial' => '+385',  'orden' => 49],
            ['code' => 'CU', 'name' => 'Cuba',                          'dial' => '+53',   'orden' => 50],
            ['code' => 'DK', 'name' => 'Dinamarca',                     'dial' => '+45',   'orden' => 51],
            ['code' => 'DJ', 'name' => 'Yibuti',                        'dial' => '+253',  'orden' => 52],
            ['code' => 'DM', 'name' => 'Dominica',                      'dial' => '+1767', 'orden' => 53],
            ['code' => 'EC', 'name' => 'Ecuador',                       'dial' => '+593',  'orden' => 54],
            ['code' => 'EG', 'name' => 'Egipto',                        'dial' => '+20',   'orden' => 55],
            ['code' => 'SV', 'name' => 'El Salvador',                   'dial' => '+503',  'orden' => 56],
            ['code' => 'AE', 'name' => 'Emiratos Árabes Unidos',        'dial' => '+971',  'orden' => 57],
            ['code' => 'ER', 'name' => 'Eritrea',                       'dial' => '+291',  'orden' => 58],
            ['code' => 'SK', 'name' => 'Eslovaquia',                    'dial' => '+421',  'orden' => 59],
            ['code' => 'SI', 'name' => 'Eslovenia',                     'dial' => '+386',  'orden' => 60],
            ['code' => 'ES', 'name' => 'España',                        'dial' => '+34',   'orden' => 61],
            ['code' => 'US', 'name' => 'Estados Unidos',                'dial' => '+1',    'orden' => 62],
            ['code' => 'EE', 'name' => 'Estonia',                       'dial' => '+372',  'orden' => 63],
            ['code' => 'SZ', 'name' => 'Esuatini',                      'dial' => '+268',  'orden' => 64],
            ['code' => 'ET', 'name' => 'Etiopía',                       'dial' => '+251',  'orden' => 65],
            ['code' => 'PH', 'name' => 'Filipinas',                     'dial' => '+63',   'orden' => 66],
            ['code' => 'FI', 'name' => 'Finlandia',                     'dial' => '+358',  'orden' => 67],
            ['code' => 'FJ', 'name' => 'Fiyi',                          'dial' => '+679',  'orden' => 68],
            ['code' => 'FR', 'name' => 'Francia',                       'dial' => '+33',   'orden' => 69],
            ['code' => 'GA', 'name' => 'Gabón',                         'dial' => '+241',  'orden' => 70],
            ['code' => 'GM', 'name' => 'Gambia',                        'dial' => '+220',  'orden' => 71],
            ['code' => 'GE', 'name' => 'Georgia',                       'dial' => '+995',  'orden' => 72],
            ['code' => 'GH', 'name' => 'Ghana',                         'dial' => '+233',  'orden' => 73],
            ['code' => 'GD', 'name' => 'Granada',                       'dial' => '+1473', 'orden' => 74],
            ['code' => 'GR', 'name' => 'Grecia',                        'dial' => '+30',   'orden' => 75],
            ['code' => 'GT', 'name' => 'Guatemala',                     'dial' => '+502',  'orden' => 0],
            ['code' => 'GN', 'name' => 'Guinea',                        'dial' => '+224',  'orden' => 77],
            ['code' => 'GQ', 'name' => 'Guinea Ecuatorial',             'dial' => '+240',  'orden' => 78],
            ['code' => 'GW', 'name' => 'Guinea-Bisáu',                  'dial' => '+245',  'orden' => 79],
            ['code' => 'GY', 'name' => 'Guyana',                        'dial' => '+592',  'orden' => 80],
            ['code' => 'HT', 'name' => 'Haití',                         'dial' => '+509',  'orden' => 81],
            ['code' => 'HN', 'name' => 'Honduras',                      'dial' => '+504',  'orden' => 82],
            ['code' => 'HU', 'name' => 'Hungría',                       'dial' => '+36',   'orden' => 83],
            ['code' => 'IN', 'name' => 'India',                         'dial' => '+91',   'orden' => 84],
            ['code' => 'ID', 'name' => 'Indonesia',                     'dial' => '+62',   'orden' => 85],
            ['code' => 'IQ', 'name' => 'Irak',                          'dial' => '+964',  'orden' => 86],
            ['code' => 'IR', 'name' => 'Irán',                          'dial' => '+98',   'orden' => 87],
            ['code' => 'IE', 'name' => 'Irlanda',                       'dial' => '+353',  'orden' => 88],
            ['code' => 'IS', 'name' => 'Islandia',                      'dial' => '+354',  'orden' => 89],
            ['code' => 'IL', 'name' => 'Israel',                        'dial' => '+972',  'orden' => 90],
            ['code' => 'IT', 'name' => 'Italia',                        'dial' => '+39',   'orden' => 91],
            ['code' => 'JM', 'name' => 'Jamaica',                       'dial' => '+1876', 'orden' => 92],
            ['code' => 'JP', 'name' => 'Japón',                         'dial' => '+81',   'orden' => 93],
            ['code' => 'JO', 'name' => 'Jordania',                      'dial' => '+962',  'orden' => 94],
            ['code' => 'KZ', 'name' => 'Kazajistán',                    'dial' => '+7',    'orden' => 95],
            ['code' => 'KE', 'name' => 'Kenia',                         'dial' => '+254',  'orden' => 96],
            ['code' => 'KG', 'name' => 'Kirguistán',                    'dial' => '+996',  'orden' => 97],
            ['code' => 'KI', 'name' => 'Kiribati',                      'dial' => '+686',  'orden' => 98],
            ['code' => 'KW', 'name' => 'Kuwait',                        'dial' => '+965',  'orden' => 99],
            ['code' => 'LA', 'name' => 'Laos',                          'dial' => '+856',  'orden' => 100],
            ['code' => 'LS', 'name' => 'Lesoto',                        'dial' => '+266',  'orden' => 101],
            ['code' => 'LV', 'name' => 'Letonia',                       'dial' => '+371',  'orden' => 102],
            ['code' => 'LB', 'name' => 'Líbano',                        'dial' => '+961',  'orden' => 103],
            ['code' => 'LR', 'name' => 'Liberia',                       'dial' => '+231',  'orden' => 104],
            ['code' => 'LY', 'name' => 'Libia',                         'dial' => '+218',  'orden' => 105],
            ['code' => 'LI', 'name' => 'Liechtenstein',                 'dial' => '+423',  'orden' => 106],
            ['code' => 'LT', 'name' => 'Lituania',                      'dial' => '+370',  'orden' => 107],
            ['code' => 'LU', 'name' => 'Luxemburgo',                    'dial' => '+352',  'orden' => 108],
            ['code' => 'MK', 'name' => 'Macedonia del Norte',           'dial' => '+389',  'orden' => 109],
            ['code' => 'MG', 'name' => 'Madagascar',                    'dial' => '+261',  'orden' => 110],
            ['code' => 'MY', 'name' => 'Malasia',                       'dial' => '+60',   'orden' => 111],
            ['code' => 'MW', 'name' => 'Malaui',                        'dial' => '+265',  'orden' => 112],
            ['code' => 'MV', 'name' => 'Maldivas',                      'dial' => '+960',  'orden' => 113],
            ['code' => 'ML', 'name' => 'Malí',                          'dial' => '+223',  'orden' => 114],
            ['code' => 'MT', 'name' => 'Malta',                         'dial' => '+356',  'orden' => 115],
            ['code' => 'MA', 'name' => 'Marruecos',                     'dial' => '+212',  'orden' => 116],
            ['code' => 'MH', 'name' => 'Islas Marshall',                'dial' => '+692',  'orden' => 117],
            ['code' => 'MR', 'name' => 'Mauritania',                    'dial' => '+222',  'orden' => 118],
            ['code' => 'MU', 'name' => 'Mauricio',                      'dial' => '+230',  'orden' => 119],
            ['code' => 'MX', 'name' => 'México',                        'dial' => '+52',   'orden' => 120],
            ['code' => 'FM', 'name' => 'Micronesia',                    'dial' => '+691',  'orden' => 121],
            ['code' => 'MD', 'name' => 'Moldavia',                      'dial' => '+373',  'orden' => 122],
            ['code' => 'MC', 'name' => 'Mónaco',                        'dial' => '+377',  'orden' => 123],
            ['code' => 'MN', 'name' => 'Mongolia',                      'dial' => '+976',  'orden' => 124],
            ['code' => 'ME', 'name' => 'Montenegro',                    'dial' => '+382',  'orden' => 125],
            ['code' => 'MZ', 'name' => 'Mozambique',                    'dial' => '+258',  'orden' => 126],
            ['code' => 'MM', 'name' => 'Myanmar',                       'dial' => '+95',   'orden' => 127],
            ['code' => 'NA', 'name' => 'Namibia',                       'dial' => '+264',  'orden' => 128],
            ['code' => 'NR', 'name' => 'Nauru',                         'dial' => '+674',  'orden' => 129],
            ['code' => 'NP', 'name' => 'Nepal',                         'dial' => '+977',  'orden' => 130],
            ['code' => 'NI', 'name' => 'Nicaragua',                     'dial' => '+505',  'orden' => 131],
            ['code' => 'NE', 'name' => 'Níger',                         'dial' => '+227',  'orden' => 132],
            ['code' => 'NG', 'name' => 'Nigeria',                       'dial' => '+234',  'orden' => 133],
            ['code' => 'NO', 'name' => 'Noruega',                       'dial' => '+47',   'orden' => 134],
            ['code' => 'NZ', 'name' => 'Nueva Zelanda',                 'dial' => '+64',   'orden' => 135],
            ['code' => 'OM', 'name' => 'Omán',                          'dial' => '+968',  'orden' => 136],
            ['code' => 'NL', 'name' => 'Países Bajos',                  'dial' => '+31',   'orden' => 137],
            ['code' => 'PK', 'name' => 'Pakistán',                      'dial' => '+92',   'orden' => 138],
            ['code' => 'PW', 'name' => 'Palaos',                        'dial' => '+680',  'orden' => 139],
            ['code' => 'PA', 'name' => 'Panamá',                        'dial' => '+507',  'orden' => 140],
            ['code' => 'PG', 'name' => 'Papúa Nueva Guinea',            'dial' => '+675',  'orden' => 141],
            ['code' => 'PY', 'name' => 'Paraguay',                      'dial' => '+595',  'orden' => 142],
            ['code' => 'PE', 'name' => 'Perú',                          'dial' => '+51',   'orden' => 143],
            ['code' => 'PL', 'name' => 'Polonia',                       'dial' => '+48',   'orden' => 144],
            ['code' => 'PT', 'name' => 'Portugal',                      'dial' => '+351',  'orden' => 145],
            ['code' => 'PR', 'name' => 'Puerto Rico',                   'dial' => '+1787', 'orden' => 146],
            ['code' => 'GB', 'name' => 'Reino Unido',                   'dial' => '+44',   'orden' => 147],
            ['code' => 'CF', 'name' => 'Rep. Centroafricana',           'dial' => '+236',  'orden' => 148],
            ['code' => 'DO', 'name' => 'Rep. Dominicana',               'dial' => '+1809', 'orden' => 149],
            ['code' => 'CZ', 'name' => 'Rep. Checa',                    'dial' => '+420',  'orden' => 150],
            ['code' => 'RW', 'name' => 'Ruanda',                        'dial' => '+250',  'orden' => 151],
            ['code' => 'RO', 'name' => 'Rumanía',                       'dial' => '+40',   'orden' => 152],
            ['code' => 'RU', 'name' => 'Rusia',                         'dial' => '+7',    'orden' => 153],
            ['code' => 'WS', 'name' => 'Samoa',                         'dial' => '+685',  'orden' => 154],
            ['code' => 'KN', 'name' => 'San Cristóbal y Nieves',        'dial' => '+1869', 'orden' => 155],
            ['code' => 'SM', 'name' => 'San Marino',                    'dial' => '+378',  'orden' => 156],
            ['code' => 'VC', 'name' => 'San Vicente y las Granadinas',  'dial' => '+1784', 'orden' => 157],
            ['code' => 'LC', 'name' => 'Santa Lucía',                   'dial' => '+1758', 'orden' => 158],
            ['code' => 'ST', 'name' => 'Santo Tomé y Príncipe',         'dial' => '+239',  'orden' => 159],
            ['code' => 'SN', 'name' => 'Senegal',                       'dial' => '+221',  'orden' => 160],
            ['code' => 'RS', 'name' => 'Serbia',                        'dial' => '+381',  'orden' => 161],
            ['code' => 'SC', 'name' => 'Seychelles',                    'dial' => '+248',  'orden' => 162],
            ['code' => 'SL', 'name' => 'Sierra Leona',                  'dial' => '+232',  'orden' => 163],
            ['code' => 'SG', 'name' => 'Singapur',                      'dial' => '+65',   'orden' => 164],
            ['code' => 'SY', 'name' => 'Siria',                         'dial' => '+963',  'orden' => 165],
            ['code' => 'SO', 'name' => 'Somalia',                       'dial' => '+252',  'orden' => 166],
            ['code' => 'LK', 'name' => 'Sri Lanka',                     'dial' => '+94',   'orden' => 167],
            ['code' => 'ZA', 'name' => 'Sudáfrica',                     'dial' => '+27',   'orden' => 168],
            ['code' => 'SD', 'name' => 'Sudán',                         'dial' => '+249',  'orden' => 169],
            ['code' => 'SS', 'name' => 'Sudán del Sur',                 'dial' => '+211',  'orden' => 170],
            ['code' => 'SE', 'name' => 'Suecia',                        'dial' => '+46',   'orden' => 171],
            ['code' => 'CH', 'name' => 'Suiza',                         'dial' => '+41',   'orden' => 172],
            ['code' => 'SR', 'name' => 'Surinam',                       'dial' => '+597',  'orden' => 173],
            ['code' => 'TH', 'name' => 'Tailandia',                     'dial' => '+66',   'orden' => 174],
            ['code' => 'TZ', 'name' => 'Tanzania',                      'dial' => '+255',  'orden' => 175],
            ['code' => 'TJ', 'name' => 'Tayikistán',                    'dial' => '+992',  'orden' => 176],
            ['code' => 'TL', 'name' => 'Timor Oriental',                'dial' => '+670',  'orden' => 177],
            ['code' => 'TG', 'name' => 'Togo',                          'dial' => '+228',  'orden' => 178],
            ['code' => 'TO', 'name' => 'Tonga',                         'dial' => '+676',  'orden' => 179],
            ['code' => 'TT', 'name' => 'Trinidad y Tobago',             'dial' => '+1868', 'orden' => 180],
            ['code' => 'TN', 'name' => 'Túnez',                         'dial' => '+216',  'orden' => 181],
            ['code' => 'TM', 'name' => 'Turkmenistán',                  'dial' => '+993',  'orden' => 182],
            ['code' => 'TR', 'name' => 'Turquía',                       'dial' => '+90',   'orden' => 183],
            ['code' => 'TV', 'name' => 'Tuvalu',                        'dial' => '+688',  'orden' => 184],
            ['code' => 'UA', 'name' => 'Ucrania',                       'dial' => '+380',  'orden' => 185],
            ['code' => 'UG', 'name' => 'Uganda',                        'dial' => '+256',  'orden' => 186],
            ['code' => 'UY', 'name' => 'Uruguay',                       'dial' => '+598',  'orden' => 187],
            ['code' => 'UZ', 'name' => 'Uzbekistán',                    'dial' => '+998',  'orden' => 188],
            ['code' => 'VU', 'name' => 'Vanuatu',                       'dial' => '+678',  'orden' => 189],
            ['code' => 'VE', 'name' => 'Venezuela',                     'dial' => '+58',   'orden' => 190],
            ['code' => 'VN', 'name' => 'Vietnam',                       'dial' => '+84',   'orden' => 191],
            ['code' => 'YE', 'name' => 'Yemen',                         'dial' => '+967',  'orden' => 192],
            ['code' => 'ZM', 'name' => 'Zambia',                        'dial' => '+260',  'orden' => 193],
            ['code' => 'ZW', 'name' => 'Zimbabue',                      'dial' => '+263',  'orden' => 194],
        ];

        foreach ($paises as $pais) {
            DB::table('paises')->updateOrInsert(
                ['code' => $pais['code']],
                [
                    'name'       => $pais['name'],
                    'dial'       => $pais['dial'],
                    'activo'     => in_array($pais['code'], $activosPorDefecto),
                    'orden'      => $pais['orden'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
